/*
 * Copyright (c) 2001-2007 Scott E. Johnston
 * Copyright (c) 1994-1999 Vectaport Inc.
 *
 * Permission to use, copy, modify, distribute, and sell this software and
 * its documentation for any purpose is hereby granted without fee, provided
 * that the above copyright notice appear in all copies and that both that
 * copyright notice and this permission notice appear in supporting
 * documentation, and that the names of the copyright holders not be used in
 * advertising or publicity pertaining to distribution of the software
 * without specific, written prior permission.  The copyright holders make
 * no representations about the suitability of this software for any purpose.
 * It is provided "as is" without express or implied warranty.
 *
 * THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
 * SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY SPECIAL,
 * INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING
 * FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
 * NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
 * WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 * 
 */

/*
 * ComValue is the general object for interpreter values stored on the
 * stack and associated with global symbols.
 */

#if !defined(_comvalue_h)
#define _comvalue_h

#include <ComTerp/_comterp.h>
#include <Attribute/attrvalue.h>
#include <Unidraw/Components/compview.h>
#include <string>

class ComFunc;
class ComTerp;

//: AttributeValue with extensions for use with ComTerp.
// ComValue adds to AttributeValue a set of convenient static methods
// for returning constants useful in any application of ComTerp, as well
// as four integers (narg(), nkey(), nids(), pedepth()) used for storing
// necessary command and keyword state after code conversion and during 
// interpretation.  
#define COMVALUE_BQUOTE_FLAG     0x01  // backquote -- return symbol without lookup
#define COMVALUE_LHS_ASSIGN_FLAG 0x02  // set by AssignFunc on global() or local() ComValue in lhs context
#define COMVALUE_LOCAL_FLAG      0x04  // set by local() on its lvalue symbol -- write the default symbol table, skipping any func frame
#define COMVALUE_COLONED_FLAG    0x08  // set by ColonListFunc -- an ArrayType built by ':', not ','
#define COMVALUE_SLICED_FLAG     0x10  // set on a StringType sliced from another string (#395) -- sliceoff()/slicelen() hold the window, narg()/nkey() read 0

class ComValue : public AttributeValue {
public:
    ComValue(const ComValue&);
    // deep copy constructor.
    ComValue(ComValue*);
    // deep copy constructor.
    ComValue(AttributeValue&);
    // copy constructor from an AttributeValue.
    ComValue(postfix_token* token);
    // copy constructor from a postfix token generated by a Parser.
    ComValue(ValueType type);
    // construct of a given 'type' with no initial value.
    ComValue();
    // construct of UnknownType.

    ComValue(char val);
    // CharType constructor.
    ComValue(unsigned char val);
    // UCharType constructor.
    ComValue(short val);
    // ShortType constructor.
    ComValue(unsigned short val);
    // UShortType constructor.
    ComValue(int val, ValueType type=IntType);
    // IntType constructor or any other int-like value.
    ComValue(unsigned int val, ValueType type=IntType);
    // UIntType constructor or any other unsigned-int-like value including SymbolType.
    ComValue(unsigned int val, unsigned int, ValueType type=KeywordType);
    // KeywordType constructor (or can be used for ObjectType).
    ComValue(long val);
    // LongType constructor.
    ComValue(unsigned long val);
    // ULongType constructor.
    ComValue(float val);
    // FloatType constructor.
    ComValue(double val);
    // DoubleType constructor.
    ComValue(int class_symid, void* ptr);
    // ObjectType constructor.
    ComValue(AttributeValueList* listptr);
    // ArrayType/ListType constructor.
    ComValue(void* funcptr, AttributeValueList* listptr);
    // StreamType constructor.
    ComValue(const char* val);
    // StringType constructor.
    ComValue(ComFunc* func);
    // CommandType constructor.
    ComValue(ComponentView* view, int compid);
    // ComponentView constructor.

    void init();
    // initialize member variables.
    virtual ~ComValue();

    ComValue& operator= (const ComValue&);
    // assignment operator.

    virtual void* geta(int type, int compid=-1); 
    // return a pointer if ObjectType matches or compid is superclass
    virtual boolean isa(int type, int compid=-1); 
    // return true if ObjectType matches or compid is superclass

    int narg() const;
    // number of arguments associated with this command or keyword; always 0
    // for a StringType, whose storage doubles as a slice's offset (#395) --
    // use sliceoff() to read that.
    int nkey() const;
    // number of keywords associated with this command; always 0 for a
    // StringType, whose storage doubles as a slice's length (#395) -- use
    // slicelen() to read that.
    int nids() const;
    // number of subordinate identifiers associated with this identifier (not used).
    void narg(int n) {_narg = n; }
    // set number of arguments associated with this command or keyword.
    void nkey(int n) {_nkey = n; }
    // set number of keywords associated with this command.
    void nids(int n) {_nids = n; }
    // set number of subordinate identifiers associated with this identifier (not used).
    int bquote() const;
    // get flag that says this SymbolType has been backquoted
    void bquote(int flag) { if(flag) _flags |= COMVALUE_BQUOTE_FLAG; else _flags &= ~COMVALUE_BQUOTE_FLAG; }
    // set flag that says this SymbolType has been backquoted
    int lhs_assign() const;
    // return flag that indicates this CommandType is on left-hand side of an assignment.
    void lhs_assign(int flag) { if(flag) _flags |= COMVALUE_LHS_ASSIGN_FLAG; else _flags &= ~COMVALUE_LHS_ASSIGN_FLAG; }
    // set flag that indicates this CommandType is on the left-hand side of an assignment.
    int local_flag() const;
    // return flag that marks a local() lvalue symbol -- assignment writes the
    // default symbol table, skipping any func frame.
    void local_flag(int flag) { if(flag) _flags |= COMVALUE_LOCAL_FLAG; else _flags &= ~COMVALUE_LOCAL_FLAG; }
    // set flag that marks a local() lvalue symbol.
    int coloned() const;
    // return flag that marks an ArrayType as built by ':' rather than ','.
    void coloned(int flag) { if(flag) _flags |= COMVALUE_COLONED_FLAG; else _flags &= ~COMVALUE_COLONED_FLAG; }
    // set flag that marks an ArrayType as built by ':' rather than ','.

    int sliced() const;
    // return flag that marks a StringType value as a slice of another
    // string, sharing its symid rather than owning a copy (#395).
    void sliced(int flag) { if(flag) _flags |= COMVALUE_SLICED_FLAG; else _flags &= ~COMVALUE_SLICED_FLAG; }
    // set flag that marks a StringType value as a slice.
    int sliceoff() const;
    // offset of a slice's window into its symid string; valid only when sliced().
    void sliceoff(int off) { _narg = off; }
    // set a slice's window offset.
    int slicelen() const;
    // length of a slice's window into its symid string; valid only when sliced().
    void slicelen(int len) { _nkey = len; }
    // set a slice's window length.

    const char* slice_cstr(std::string& scratch);
    // NUL-terminated text of a StringType value -- string_ptr() narrowed to
    // [sliceoff(), sliceoff()+slicelen()) when sliced() (#395), otherwise
    // string_ptr() itself.  Takes a caller-owned std::string rather than a
    // ComValue member: _stack (comterp.c) grows via dmm_realloc, a raw
    // realloc of the whole ComValue array, so ComValue must stay a plain,
    // trivially-relocatable union -- no non-POD member survives that move.

    int& pedepth() { return _pedepth; }
    // set/get depth of nesting in post-evaluated blocks of control commands.
    // Used by ComTerp to efficiently extract and execute post-evaluation commands.

    boolean unknown() { return ComValue::UnknownType == type(); }
    // return true if UnknownType.
    boolean null() { return unknown(); }
    // return true if UnknownType.
    boolean is_comfunc(int func_classid);
    // returns true if CommandType with ComFunc

    friend ostream& operator << (ostream& s, const ComValue&);
    // print contents to ostream, brief or not depending on
    // associated ComTerp brief flag.
    virtual const char* String();
    // generate string using << operator

    static void comterp(const ComTerp* comterp) { _comterp = comterp; }
    // set static pointer to ComTerp used to provide brief flag.
    static const ComTerp* comterp() { return _comterp; }
    // return static pointer to ComTerp used to provide brief flag.

    static ComValue& nullval();
    // returns reference to UnknownType ComValue.
    static ComValue& trueval();
    // returns reference to BooleanType ComValue with value of 1.
    static ComValue& falseval();
    // returns reference to BooleanType ComValue with value of 0.
    static ComValue& blankval();
    // returns reference to BlankType ComValue.  ComTerp places one of these
    // on the stack whenever the execution of a ComFunc places nothing on the stack.
    static ComValue& unkval();
    // returns reference to UnknownType ComValue.
    static ComValue& oneval();
    // returns reference to IntType ComValue with value of 1.
    static ComValue& zeroval();
    // returns reference to IntType ComValue with value of 0.
    static ComValue& minusoneval();
    // returns reference to IntType ComValue with value of -1.
    static ComValue& twoval();
    // returns reference to IntType ComValue with value of 2.
    static ComValue& acharval();
    // returns reference to CharType ComValue with value of 'a'.

    unsigned linenum() const { return _linenum; }
    // Get line number of command in script file.
    void linenum(unsigned ln) { _linenum=ln; }
    // Set line number of command in script file.

    boolean is_funcobj(ComTerp*);
    // return true if ObjectType of FuncObj of symbol resolves to same
    boolean is_fileobj();
    // return true if ObjectType of FileObj
    boolean is_pipeobj();
    // return true if ObjectType of PipeObj
    boolean is_socketobj();
    // return true if ObjectType of SocketObj
    boolean is_dateobj();
    // return true if ObjectType of DateObj

protected:
    void zero_vals() { _narg = _nkey = _nids = _pedepth = _flags = 0; }

    int _narg;
    int _nkey;
    int _nids;
    int _pedepth;
    int _flags;  // bitfield: COMVALUE_BQUOTE_FLAG, COMVALUE_LHS_ASSIGN_FLAG, ...
    unsigned _linenum;

    static const ComTerp* _comterp;
    static ComValue _nullval;
    static ComValue _trueval;
    static ComValue _falseval;
    static ComValue _blankval;
    static ComValue _unkval;
    static ComValue _oneval;
    static ComValue _zeroval;
    static ComValue _minusoneval;
    static ComValue _twoval;
    static ComValue _acharval;
};

#endif /* !defined(_comvalue_h) */
