#!/bin/sh
# 
# generate a Makefile from an Imakefile outside of the source tree
# 

usage="usage: $0 [-a]"
do_all=

case "$#" in
	0)	;;
	1)	case "$1" in
			-a)	do_all="yes"
				;;
			*)	echo "$usage" 1>&2; exit 1
				;;
		esac
		;;
	*)	echo "$usage" 1>&2; exit 1
		;;
esac

if [ -f Makefile ]; then 
	rm -f Makefile.bak
	mv Makefile Makefile.bak
fi


case "$do_all" in
	yes)	set -x
		imake -T "template" -I/usr/X11R6/lib/ivtools -I/usr/X11R6/lib/ivtools/.. -I/usr/X11R6/lib/X11/config  -DUseInstalled &&
		make Makefile ARCH=LINUX CONFIGSRC=/usr/X11R6/lib/ivtools XCONFIGDIR=/usr/X11R6/lib/X11/config  &&
		make Makefiles ARCH=LINUX CONFIGSRC=/usr/X11R6/lib/ivtools XCONFIGDIR=/usr/X11R6/lib/X11/config  &&
		make depend
		;;
	*)	set -x
		imake -T "template" -I/usr/X11R6/lib/ivtools -I/usr/X11R6/lib/ivtools/.. -I/usr/X11R6/lib/X11/config  -DUseInstalled
		;;
esac

