package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// writeGoArchivePkg writes the compiled sort body into gosort/sort.go --
// regenerating the file each run from the real compileSortFunc output,
// rather than hand-editing it, so it stays true to "compiled from the
// func's tree, not hand-written" -- and builds it as a c-archive: the
// ComTerp->Go direction of the boundary (cgo only ever covers Go->C/C++).
// The resulting .a/.h pair is what the new ComFunc built-in links against.
func writeGoArchivePkg(dir, body string) error {
	src := fmt.Sprintf(goArchiveTmpl, body)
	if err := os.WriteFile(filepath.Join(dir, "sort.go"), []byte(src), 0644); err != nil {
		return err
	}
	build := exec.Command("go", "build", "-buildmode=c-archive", "-o", "libgosort.a", ".")
	build.Dir = dir
	build.Env = append(os.Environ(), "CGO_ENABLED=1")
	if out, err := build.CombinedOutput(); err != nil {
		return fmt.Errorf("go build -buildmode=c-archive: %w\n%s", err, out)
	}
	return nil
}

const goArchiveTmpl = `// Code generated by the comcomp funccompile spike from the isort ComTerp
// func's own postfix(:tree); DO NOT EDIT.
package main

import "C"

import (
	"strconv"
	"strings"
)

func GoInsertionSort(arr []int64) []int64 {
%s
	return arr
}

// SortIntsCSV is the exported boundary the GoSortFunc ComFunc built-in
// calls: one CSV string in, one CSV string out, so timing the Go side
// never pays for per-element ComValue marshaling.
//export SortIntsCSV
func SortIntsCSV(csv *C.char) *C.char {
	s := C.GoString(csv)
	var arr []int64
	if s != "" {
		parts := strings.Split(s, ",")
		arr = make([]int64, len(parts))
		for i, p := range parts {
			v, _ := strconv.ParseInt(p, 10, 64)
			arr[i] = v
		}
	}
	arr = GoInsertionSort(arr)
	strs := make([]string, len(arr))
	for i, v := range arr {
		strs[i] = strconv.FormatInt(v, 10)
	}
	return C.CString(strings.Join(strs, ","))
}

func main() {}
`
