package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// writeAndRunSortProgram wraps the compiled sort body in a standalone Go
// program that takes its input the way Scott asked: one serialized CSV
// string in, parsed to a native []int64 once, sorted with no further
// ComTerp-side marshaling, serialized back to one CSV string out -- so a
// timing comparison measures Go's own execution, not per-element
// boundary-crossing overhead. This is the same shape the real ComFunc
// built-in's call into the exported Go function will use; this program
// just drives it directly, no C archive yet, to validate the generated
// body before wiring that up.
func writeAndRunSortProgram(dir, body string, n int) error {
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	program := fmt.Sprintf(sortProgramTmpl, body, n)
	if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte(program), 0644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module comcomp_sort_gen\n\ngo 1.21\n"), 0644); err != nil {
		return err
	}

	build := exec.Command("go", "build", "-o", "sortgen_bin", ".")
	build.Dir = dir
	if out, err := build.CombinedOutput(); err != nil {
		return fmt.Errorf("go build: %w\n%s", err, out)
	}

	run := exec.Command("./sortgen_bin")
	run.Dir = dir
	out, err := run.CombinedOutput()
	fmt.Print(string(out))
	return err
}

const sortProgramTmpl = `// Code generated by the comcomp funccompile spike; DO NOT EDIT.
package main

import (
	"fmt"
	"strconv"
	"strings"
	"time"
)

// GoInsertionSort is compiled straight from the ComTerp func's own
// postfix(:tree) -- not hand-written -- by funccompile.go's compileSortFunc.
func GoInsertionSort(arr []int64) []int64 {
%s
	return arr
}

// SortIntsCSV is the exported boundary this spike's later ComFunc built-in
// calls: one string in, one string out, matching the real built-in's
// signature so this timing run is representative of it.
func SortIntsCSV(csv string) string {
	parts := strings.Split(csv, ",")
	arr := make([]int64, len(parts))
	for i, p := range parts {
		v, _ := strconv.ParseInt(p, 10, 64)
		arr[i] = v
	}
	arr = GoInsertionSort(arr)
	strs := make([]string, len(arr))
	for i, v := range arr {
		strs[i] = strconv.FormatInt(v, 10)
	}
	return strings.Join(strs, ",")
}

func mklist(n int) string {
	strs := make([]string, n)
	for i := 0; i < n; i++ {
		strs[i] = strconv.FormatInt(int64((int64(i)*2654435761)%%10000), 10)
	}
	return strings.Join(strs, ",")
}

func main() {
	n := %d
	csv := mklist(n)

	t0 := time.Now()
	sortedCSV := SortIntsCSV(csv)
	elapsed := time.Since(t0)

	parts := strings.Split(sortedCSV, ",")
	ok := true
	prev := int64(-1 << 62)
	for _, p := range parts {
		v, _ := strconv.ParseInt(p, 10, 64)
		if v < prev {
			ok = false
		}
		prev = v
	}
	fmt.Printf("GoInsertionSort(n=%%d) elapsed_ns=%%d ok=%%v first5=%%v\n", n, elapsed.Nanoseconds(), ok, parts[:5])
}
`
