// Code generated by the comcomp funccompile spike from the isort ComTerp
// func's own postfix(:tree); DO NOT EDIT.
package main

import "C"

import (
	"strconv"
	"strings"
)

func GoInsertionSort(arr []int64) []int64 {
	n := int64(len(arr))
	for i := int64(1); (i < n); i = (i + int64(1)) {
		key := arr[i]
		j := (i - int64(1))
		for ((j >= int64(0)) && (arr[j] > key)) {
			arr[(j + int64(1))] = arr[j]
			j = (j - int64(1))
		}
		arr[(j + int64(1))] = key
	}

	return arr
}

// SortIntsCSV is the exported boundary the GoSortFunc ComFunc built-in
// calls: one CSV string in, one CSV string out, so timing the Go side
// never pays for per-element ComValue marshaling.
//export SortIntsCSV
func SortIntsCSV(csv *C.char) *C.char {
	s := C.GoString(csv)
	var arr []int64
	if s != "" {
		parts := strings.Split(s, ",")
		arr = make([]int64, len(parts))
		for i, p := range parts {
			v, _ := strconv.ParseInt(p, 10, 64)
			arr[i] = v
		}
	}
	arr = GoInsertionSort(arr)
	strs := make([]string, len(arr))
	for i, v := range arr {
		strs[i] = strconv.FormatInt(v, 10)
	}
	return C.CString(strings.Join(strs, ","))
}

func main() {}
