// Command compile_poc is the second half of the comcomp spike: given a
// .comt expression, it gets the real ComTerp parse tree (via
// postfix(expr :tree), the same mechanism comlint already uses), compiles
// it to Go -- native Go arithmetic wherever the whole subtree is built
// from hand-written primitives (integer +-*/ , for this spike), falling
// back to a bridge call through real ComTerp for anything else -- and
// then actually builds and runs the generated Go program, so the result
// is a real compile, not a simulation.
package main

/*
#cgo CXXFLAGS: -std=gnu++17 -I${SRCDIR}/../.. -I${SRCDIR}/../../include -I${SRCDIR}/../../include/ivstd -I${SRCDIR}/../../include/ACE-lite
#cgo LDFLAGS: -L${SRCDIR}/../../ComTerp/LINUX -lComTerp -L${SRCDIR}/../../ComUtil/LINUX -lComUtil -L${SRCDIR}/../../Attribute/LINUX -lAttribute -L${SRCDIR}/../../TopoFace/LINUX -lTopoFace -L${SRCDIR}/../../Time/LINUX -lTime -L${SRCDIR}/../../Unidraw-common/LINUX -lUnidraw-common -L${SRCDIR}/../../IV-common/LINUX -lIV-common -L${SRCDIR}/../../ACE-lite/LINUX -lACE-lite -Wl,-rpath,${SRCDIR}/../../ComTerp/LINUX -Wl,-rpath,${SRCDIR}/../../ComUtil/LINUX -Wl,-rpath,${SRCDIR}/../../Attribute/LINUX -Wl,-rpath,${SRCDIR}/../../TopoFace/LINUX -Wl,-rpath,${SRCDIR}/../../Time/LINUX -Wl,-rpath,${SRCDIR}/../../Unidraw-common/LINUX -Wl,-rpath,${SRCDIR}/../../IV-common/LINUX -Wl,-rpath,${SRCDIR}/../../ACE-lite/LINUX -lstdc++
#include "shim.h"
#include <stdlib.h>
*/
import "C"

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"unsafe"
)

func bridgeEval(h C.comterp_handle, expr string) (string, error) {
	cexpr := C.CString(expr)
	defer C.free(unsafe.Pointer(cexpr))
	result := C.comterp_bridge_eval(h, cexpr)
	if result == nil {
		return "", fmt.Errorf("%s", C.GoString(C.comterp_bridge_errmsg(h)))
	}
	return C.GoString(result), nil
}

func main() {
	expr := "1+2*3"
	if len(os.Args) > 1 {
		expr = os.Args[1]
	}

	h := C.comterp_bridge_new()
	defer C.comterp_bridge_free(h)

	groundTruth, err := bridgeEval(h, expr)
	if err != nil {
		fmt.Fprintf(os.Stderr, "concomp: evaluating %q directly: %s\n", expr, err)
		os.Exit(1)
	}

	treeText, err := bridgeEval(h, "postfix("+expr+" :tree)")
	if err != nil {
		fmt.Fprintf(os.Stderr, "concomp: getting parse tree for %q: %s\n", expr, err)
		os.Exit(1)
	}

	tree, err := parseTree(treeText)
	if err != nil {
		fmt.Fprintf(os.Stderr, "concomp: parsing tree %q: %s\n", treeText, err)
		os.Exit(1)
	}

	c := compileNode(tree)

	fmt.Printf("expr:          %s\n", expr)
	fmt.Printf("parse tree:    %s\n", treeText)
	fmt.Printf("compiled Go:   %s\n", c.goExpr)
	fmt.Printf("fully native:  %v (expected bridge calls at runtime: %d)\n", c.native, c.fallback)
	fmt.Printf("ground truth:  %s (evaluated directly, not compiled)\n", groundTruth)

	genDir, err := filepath.Abs("generated")
	if err != nil {
		fmt.Fprintf(os.Stderr, "concomp: %s\n", err)
		os.Exit(1)
	}
	if err := generateAndRun(genDir, c.goExpr); err != nil {
		fmt.Fprintf(os.Stderr, "concomp: generated program failed: %s\n", err)
		os.Exit(1)
	}
}

func generateAndRun(dir string, goExpr string) error {
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	for _, name := range []string{"shim.h", "shim.cc"} {
		src, err := os.ReadFile(name)
		if err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(dir, name), src, 0644); err != nil {
			return err
		}
	}
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module comcomp_generated\n\ngo 1.21\n"), 0644); err != nil {
		return err
	}
	program := generatedProgram(goExpr)
	if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte(program), 0644); err != nil {
		return err
	}

	build := exec.Command("go", "build", "-o", "generated_bin", ".")
	build.Dir = dir
	build.Env = append(os.Environ(), "CGO_ENABLED=1")
	if out, err := build.CombinedOutput(); err != nil {
		return fmt.Errorf("go build: %w\n%s", err, out)
	}

	run := exec.Command("./generated_bin")
	run.Dir = dir
	out, err := run.CombinedOutput()
	fmt.Printf("generated run: %s", out)
	return err
}

func generatedProgram(goExpr string) string {
	const tmpl = `// Code generated by compile_poc; DO NOT EDIT.
package main

/*
%s
#include "shim.h"
#include <stdlib.h>
*/
import "C"

import (
	"fmt"
	"os"
	"strconv"
	"unsafe"
)

var fallbackCalls int

// evalInt is the fallback tier: evaluate the given ComTerp source through
// the bridge for any node compileNode couldn't emit as native Go.
func evalInt(h C.comterp_handle, expr string) int64 {
	fallbackCalls++
	cexpr := C.CString(expr)
	defer C.free(unsafe.Pointer(cexpr))
	result := C.comterp_bridge_eval(h, cexpr)
	if result == nil {
		fmt.Fprintf(os.Stderr, "evalInt(%%q): %%s\n", expr, C.GoString(C.comterp_bridge_errmsg(h)))
		os.Exit(1)
	}
	v, err := strconv.ParseInt(C.GoString(result), 10, 64)
	if err != nil {
		fmt.Fprintf(os.Stderr, "evalInt(%%q): non-integer result %%q\n", expr, C.GoString(result))
		os.Exit(1)
	}
	return v
}

func main() {
	h := C.comterp_bridge_new()
	defer C.comterp_bridge_free(h)

	result := %s
	fmt.Printf("result=%%d fallback_calls=%%d\n", result, fallbackCalls)
}
`
	cgoDirectives := "#cgo CXXFLAGS: -std=gnu++17 -I${SRCDIR}/../../.. -I${SRCDIR}/../../../include -I${SRCDIR}/../../../include/ivstd -I${SRCDIR}/../../../include/ACE-lite\n" +
		"#cgo LDFLAGS: -L${SRCDIR}/../../../ComTerp/LINUX -lComTerp -L${SRCDIR}/../../../ComUtil/LINUX -lComUtil -L${SRCDIR}/../../../Attribute/LINUX -lAttribute -L${SRCDIR}/../../../TopoFace/LINUX -lTopoFace -L${SRCDIR}/../../../Time/LINUX -lTime -L${SRCDIR}/../../../Unidraw-common/LINUX -lUnidraw-common -L${SRCDIR}/../../../IV-common/LINUX -lIV-common -L${SRCDIR}/../../../ACE-lite/LINUX -lACE-lite -Wl,-rpath,${SRCDIR}/../../../ComTerp/LINUX -Wl,-rpath,${SRCDIR}/../../../ComUtil/LINUX -Wl,-rpath,${SRCDIR}/../../../Attribute/LINUX -Wl,-rpath,${SRCDIR}/../../../TopoFace/LINUX -Wl,-rpath,${SRCDIR}/../../../Time/LINUX -Wl,-rpath,${SRCDIR}/../../../Unidraw-common/LINUX -Wl,-rpath,${SRCDIR}/../../../IV-common/LINUX -Wl,-rpath,${SRCDIR}/../../../ACE-lite/LINUX -lstdc++"
	return fmt.Sprintf(tmpl, cgoDirectives, goExpr)
}
